# config.yaml （请严格复制此内容，不要手动输入）
constants:
  planck_constant: 6.62607015e-34  # 普朗克常数 h, J·s
  speed_of_light: 2.99792458e8     # 光速 c, m/s
  boltzmann_constant: 1.380649e-23 # 玻尔兹曼常数 k, J/K


TIR_bands:  # 热红外波段信息
  band_numbers: [7, 8, 9, 10, 11, 12]     #pyhton中的索引从0开始，所以这里的索引是7-12
  band_names: ['TIR_27', 'TIR_28', 'TIR_29', 'TIR_30', 'TIR_31', 'TIR_32']

modis_parameters: #热红外波段的辐射定标参数
  wavelengths: [6.715e-6, 7.325e-6, 8.550e-6, 9.730e-6, 11.030e-6, 12.020e-6]  # 波段27-32的中心波长 (单位: 米)
  radiance_scales: [0.000117557, 0.00019245, 0.000532487, 0.000406323, 0.000840022, 0.000729698]  # 波段27-32的辐射尺度
  radiance_offsets: [2730.5833, 2317.4883, 2730.5835, 1560.3333, 1577.3397, 1658.2213]  # 波段27-32的辐射偏移
  emissivity_coefficients:  # 发射率计算参数
    slope: 0.002  # 发射率计算斜率
    intercept: 0.49  # 发射率计算截距
  lst_coefficients:  # 地表温度计算参数
    slope: 0.02  # 地表温度计算斜率